### ISSUE TITLE
Unexpected behavior for terminal/ssh buffers

### ISSUE THREAD

**Issue by al-ce** [volskaya/windovigation.nvim#1]
When I focus a terminal buffer, or a buffer opened via ssh (e.g. `nvim scp://user@hostname`), for a second time *after* it's already been read (whether from the same window, different window, different tab, etc.) I receive the warning from the associated line in utils.lua:

https://github.com/volskaya/windovigation.nvim/blob/af5845ea9e9a3149aaa8aaad99dae31dc60485a5/lua/windovigation/utils.lua#L47-L49

Here's an example output of `vim.fn.expand('%')` for these situations:
`term://~/.config/nvim//185059:/usr/bin/zsh`
`scp://user@hostname/.bashrc`

Some relevant information is at `:h terminal-start` and `:h default-autocmds` and `:h netrw`. (edit: my suggestion is that these type of files, and probably ftp files, should maybe count as absolute paths here)

Another terminal/ssh buffer issue comes up due to, I believe, the `layout.handle_layout_change()` function and the `utils.maybe_close_buffer_for_file()` function. Suppose you have a split window with a terminal/ssh buffer open (the only window that has that buffer), and you close that window.  Then open a split window again, then open that same buffer, and finally close that window again. (imagine toggling a show/hide of that terminal buffer in a split window like the bottom-panel in VS Code).

On that second window-close command, this condition evaluates to true and deletes the terminal/ssh buffer:

https://github.com/volskaya/windovigation.nvim/blob/af5845ea9e9a3149aaa8aaad99dae31dc60485a5/lua/windovigation/utils.lua#L65-L67

This evaluation isn't unique to terminal/ssh buffers. But if you were to reopen the terminal buffer expecting to see your previous work in that terminal, it would be gone, unlike a regular buffer, where so long as you saved your work before deletion, your work is still preserved. And since working over ssh isn't always zippy, re-opening a file over ssh is noticeably slower than browsing to it via the bufist.

(worth noting that even when a normal buffer is removed from the buffer list in this instance, this may be an issue for people who use e.g. `Telescope buffers` to navigate or aren't expecting a BufDelete event for whatever reason)

Would adding a separate handler for the `TermOpen` event or something similar help with these two issues (the warning and the terminal buffer deletion)? I'm hacking my way around it by adding a condition to ignore the file deletion if its buftype == `terminal` in my fork, but I assume that will introduce unintended behavior at some point. Not sure what to do for files opened over ssh.

Hope this wasn't too verbose. I'm assuming this same issue applies to files over ftp. For what it's worth, my personal workflow doesn't actually use windovigation's commands in windows/tabs with terminal buffers. This is a great plugin! Thanks for sharing it.

Tested with this lazy.nvim config:

<details>
  <summary>Click to expand</summary>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  "nvim-lua/plenary.nvim",
  {
    "nvim-telescope/telescope.nvim",
    lazy = false,
    config = true,
    keys = {
      {
        "<M-b>",
        function()
          require("telescope.builtin").buffers()
        end,
        desc = "Telescope: buffers",
      },
      {
        "<M-f>",
        function()
          require("telescope.builtin").find_files()
        end,
        desc = "Telescope: Find Files (cwd)",
      },
    },
  },
  {
    "volskaya/windovigation.nvim",
    lazy = false,
    config = true,
    keys = {
      {
        "<BS>",
        function()
          require("windovigation.actions").move_to_previous_file()
        end,
        desc = "WinNav - Prev",
      },
      {
        "<Del>",
        function()
          require("windovigation.actions").move_to_next_file()
        end,
        desc = "WinNav - Next",
      },
    },
  },
}, {})

vim.keymap.set("n", "<C-q>", "<cmd>qa<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<M-down>", "<c-w>j", { desc = "Move to window below" })
vim.keymap.set("n", "<M-up>", "<c-w>k", { desc = "Move to window above" })
vim.keymap.set("n", "<M-left>", "<c-w>h", { desc = "Move to window left" })
vim.keymap.set("n", "<M-right>", "<c-w>l", { desc = "Move to window right" })
```

</details>

**Comment by volskaya** [comment]
Thanks for filling the issue!

I appreciate the verbose explanation, it helped me find a lot of stuff that can be improved.

I'm about to merge quite a lot of changes off this issue, like:

1. Terminals will be scoped in the history and won't get destroyed when switching away from them, by the out of scope line you mentioned.

Though, since nvim doesn't reopen terminal buffers when sessions are restored, they wont be restored in the history either. I'm not sure if it's expected for them to be restored by the plugin, because it feels like then the plugin would also be performing session restoration work, even though it should just handle histories and buffer switching.

2. Also fixed switching into terminals. I was incorrectly using `:edit` to switch, but it only makes sense to edit regular files.

3. Refactored to use file names only off `nvim_buf_get_name`. The `event.file` ones I used before, have been are inconsistent.

4. There won't be relative / absolute paths anymore, only the buffer file name, which could be anything. Files still should be able to be fronted with a relative path.

5. Added some handling around the `nofile` buffers so they close properly and the user doesn't switch away from them with the `move_` keys.

6. Added an option `no_close_buftype` with which you can control whether a terminal gets closed, when it goes out of scope in our histories.

I've prepared a pr at #2. Gonna sleep on this, but from testing right now, the remote buffers seem to switch and restore correctly for me and terminals aren't being dropped too, except when closing nvim.

If you're interested, you can try the changes out too by using `branch = "issue_1"` in the lazy config, like:

```lua
  {
    "volskaya/windovigation.nvim",
    branch = "issue_1",
    lazy = false,
    config = true,
    opts = {
      no_close_buftype = { "terminal" },
    },
    keys = {
      {
        "<BS>",
        function()
          require("windovigation.actions").move_to_previous_file()
        end,
        desc = "WinNav - Prev",
      },
      {
        "<Del>",
        function()
          require("windovigation.actions").move_to_next_file()
        end,
        desc = "WinNav - Next",
      },
    },
  },
```

**Comment by al-ce** [comment]
Thanks very much for working on this! That PR is a lot of work! I'll take the day to use it in my regular workflow and double check everything, but on an initial check with the scenarios I described above, using the PR branch and your config, things are looking good.

> Though, since nvim doesn't reopen terminal buffers when sessions are restored, they wont be restored in the history either. 

yes, this is my experience with sessions as I've used them, though maybe there's some tmux/zellij magic that I assume wouldn't be affected here.

Really appreciate it!

**Comment by volskaya** [comment]
Okay, should be fixed now.

By the way @al-ce, I found out there is a way to enable terminal restoration. There are some options, like `terminal`, that need to be added to `vim.opt.sessionoptions`. The other options for `help`, `blank`, etc, are needed too or else nvim may close the windows with those special buffers and break history.

###### Example
```lua
vim.opt.sessionoptions = {
  -- Windovigation required options.
  "buffers",
  "help",
  "blank",
  "terminal",
  "winsize",
  "tabpages",
  -- Other options.
  "curdir",
  "globals",
  "folds",
}
```
